apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: miki-tnt/sa5g-go-usvc-k8s-addsvc
      custom:
        buildCommand: make dev_docker_addsvc
        dependencies:
          paths:
            - cmd/addsvc/main.go
            - pkg/addsvc
    - image: miki-tnt/sa5g-go-usvc-k8s-foosvc
      custom:
        buildCommand: make dev_docker_foosvc
        dependencies:
          paths:
            - cmd/foosvc/main.go
            - pkg/foosvc
    - image: miki-tnt/sa5g-go-usvc-k8s-preamblesvc
      custom:
        buildCommand: make dev_docker_preamblesvc
        dependencies:
          paths:
            - cmd/preamblesvc/main.go
            - pkg/preamblesvc
    - image: miki-tnt/sa5g-go-usvc-k8s-router
      custom:
        buildCommand: make dev_docker_router
        dependencies:
          paths:
            - cmd
            - pkg/router
            - pkg/foosvc
            - pkg/addsvc
            - pkg/preamblesvc
    - image: miki-tnt/sa5g-go-usvc-k8s-website
      context: deployments/k8s/website
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
  local: {}
deploy:
  kubectl:
    manifests:
      - ./deployments/k8s/*.yaml
profiles:
  - name: debug
    patches:
      - op: replace
        path: /build/artifacts/0/custom/buildCommand
        value: make debug_docker_addsvc
#      - op: replace
#        path: /build/artifacts/1/custom/buildCommand
#        value: make debug_docker_foosvc
#      - op: replace
#        path: /build/artifacts/2/custom/buildCommand
#        value: make debug_docker_router
