// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.2
// source: preamblesvc.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PreambleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg int64 `protobuf:"varint,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PreambleRequest) Reset() {
	*x = PreambleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_preamblesvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreambleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreambleRequest) ProtoMessage() {}

func (x *PreambleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_preamblesvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreambleRequest.ProtoReflect.Descriptor instead.
func (*PreambleRequest) Descriptor() ([]byte, []int) {
	return file_preamblesvc_proto_rawDescGZIP(), []int{0}
}

func (x *PreambleRequest) GetMsg() int64 {
	if x != nil {
		return x.Msg
	}
	return 0
}

type PreambleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rs  int64  `protobuf:"varint,1,opt,name=rs,proto3" json:"rs,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *PreambleReply) Reset() {
	*x = PreambleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_preamblesvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreambleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreambleReply) ProtoMessage() {}

func (x *PreambleReply) ProtoReflect() protoreflect.Message {
	mi := &file_preamblesvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreambleReply.ProtoReflect.Descriptor instead.
func (*PreambleReply) Descriptor() ([]byte, []int) {
	return file_preamblesvc_proto_rawDescGZIP(), []int{1}
}

func (x *PreambleReply) GetRs() int64 {
	if x != nil {
		return x.Rs
	}
	return 0
}

func (x *PreambleReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_preamblesvc_proto protoreflect.FileDescriptor

var file_preamblesvc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x6c, 0x65, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x23, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x61, 0x6d,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x31, 0x0a, 0x0d,
	0x50, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x72, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32,
	0x43, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x6c, 0x65, 0x73, 0x76, 0x63, 0x12, 0x34,
	0x0a, 0x08, 0x50, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_preamblesvc_proto_rawDescOnce sync.Once
	file_preamblesvc_proto_rawDescData = file_preamblesvc_proto_rawDesc
)

func file_preamblesvc_proto_rawDescGZIP() []byte {
	file_preamblesvc_proto_rawDescOnce.Do(func() {
		file_preamblesvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_preamblesvc_proto_rawDescData)
	})
	return file_preamblesvc_proto_rawDescData
}

var file_preamblesvc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_preamblesvc_proto_goTypes = []interface{}{
	(*PreambleRequest)(nil), // 0: pb.PreambleRequest
	(*PreambleReply)(nil),   // 1: pb.PreambleReply
}
var file_preamblesvc_proto_depIdxs = []int32{
	0, // 0: pb.Preamblesvc.Preamble:input_type -> pb.PreambleRequest
	1, // 1: pb.Preamblesvc.Preamble:output_type -> pb.PreambleReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_preamblesvc_proto_init() }
func file_preamblesvc_proto_init() {
	if File_preamblesvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_preamblesvc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreambleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_preamblesvc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreambleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_preamblesvc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_preamblesvc_proto_goTypes,
		DependencyIndexes: file_preamblesvc_proto_depIdxs,
		MessageInfos:      file_preamblesvc_proto_msgTypes,
	}.Build()
	File_preamblesvc_proto = out.File
	file_preamblesvc_proto_rawDesc = nil
	file_preamblesvc_proto_goTypes = nil
	file_preamblesvc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PreamblesvcClient is the client API for Preamblesvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PreamblesvcClient interface {
	Preamble(ctx context.Context, in *PreambleRequest, opts ...grpc.CallOption) (*PreambleReply, error)
}

type preamblesvcClient struct {
	cc grpc.ClientConnInterface
}

func NewPreamblesvcClient(cc grpc.ClientConnInterface) PreamblesvcClient {
	return &preamblesvcClient{cc}
}

func (c *preamblesvcClient) Preamble(ctx context.Context, in *PreambleRequest, opts ...grpc.CallOption) (*PreambleReply, error) {
	out := new(PreambleReply)
	err := c.cc.Invoke(ctx, "/pb.Preamblesvc/Preamble", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PreamblesvcServer is the server API for Preamblesvc service.
type PreamblesvcServer interface {
	Preamble(context.Context, *PreambleRequest) (*PreambleReply, error)
}

// UnimplementedPreamblesvcServer can be embedded to have forward compatible implementations.
type UnimplementedPreamblesvcServer struct {
}

func (*UnimplementedPreamblesvcServer) Preamble(context.Context, *PreambleRequest) (*PreambleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Preamble not implemented")
}

func RegisterPreamblesvcServer(s *grpc.Server, srv PreamblesvcServer) {
	s.RegisterService(&_Preamblesvc_serviceDesc, srv)
}

func _Preamblesvc_Preamble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreambleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreamblesvcServer).Preamble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Preamblesvc/Preamble",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreamblesvcServer).Preamble(ctx, req.(*PreambleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Preamblesvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Preamblesvc",
	HandlerType: (*PreamblesvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Preamble",
			Handler:    _Preamblesvc_Preamble_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "preamblesvc.proto",
}
